name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: Nahida-mint/kernel-5.15
          ref: master
          path: kernel-source
          
      - name: Set script permissions
        run: |
          chmod +x $GITHUB_WORKSPACE/kernel-source/scripts/*.sh
          chmod +x $GITHUB_WORKSPACE/kernel-source/scripts/*.py
          find $GITHUB_WORKSPACE/kernel-source/scripts/ -name "*.sh" -exec chmod +x {} \;
          find $GITHUB_WORKSPACE/kernel-source/scripts/ -name "*.py" -exec chmod +x {} \;
          
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Nahida-mint/kernel-5.15
          kernel-branch: master
          config: crux_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
